version: '3.9'

services:
  php-env:
    build: .
    container_name: 'app_server_3C_FP'
    volumes:
      - ./src:/var/www/html
    ports:
      - 9002:80
  mysql_db:
    image: mysql:latest
    container_name: 'db_server_3C_FP'
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: 'dbms_software_3C_FP'
    environment:
      PMA_HOST: mysql_db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 9003:80